### ISSUE TITLE
FireDM GUI displays all video clips but does not download any

### ISSUE THREAD

**Issue by edde11** [afzl-wtu/firedm#6]
Hi. Thanks for your attempt of fixing FireDM. As already posted in the other thread, it does not download any clip at the moment. Are you still working on this or is it definitely dead now?

By the way, also your custom downloader you offered here is very nice. Big congrats on that!

**Comment by altadr** [comment]
Recently I tried downloading with FireDM 2022.2.5 as provided by afzl-wtu, 

and it did work!

The only restriction I noticed was, that 
after copying a URL into the home window 
not only the actually existing streams 
are listed, but also 'non-existing' ones, 
recognizable by the size ( 0 B ).

The usability restriction is, 
that by default the uppermost item 
is highlighted and preselected, 
unregarded that this one often is empty ( 0 B ) .


So I have to select manually 
a stream with an existing size 
before starting the download. 


For a single download 
this is not a big problem, 

but for downloading a larger playlist 
it becomes really inconvenient, 
because every single item on the list 
must be handled this way separately ...

Once again thank you to afzl-wtu 
for providing the download of FireDM 2022.2.5, 

and hopefully it can be maintained in the future ...

**Comment by edde11** [comment]
I cannot confirm that. For most of the clips it has been showing me "size unknown" (also before when the old version was still working) and none of them was downloading. The clips were also valid because trying with the offered custom downloader worked without problems. I also don't understand why it is behaving that way because I thought only that yt-dlp was replaced or am I wrong? 
Anyway, it would be really great if someone could bring that great software back to life again . . .

**Comment by afzl-wtu** [comment]
I am using My custom downloader on Windows device and yt-dlp binary directly on linux now a days. FireDM is also not working for my self. I am not developer of Yt-dlp. But planning to fix yt-dlp.

**Comment by edde11** [comment]
Great! Thank you!

**Comment by afzl-wtu** [comment]
Fixed
